#!/usr/bin/env bash
set -euo pipefail

# MirrorDNA Pre-commit Hook Installer
# Installs git hooks for automated compliance validation

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"
HOOK_FILE="$HOOKS_DIR/pre-commit"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

usage() {
    cat <<EOF
MirrorDNA Pre-commit Hook Installer

Usage:
  $(basename "$0") [OPTIONS]

Options:
  --install         Install pre-commit hook (default)
  --uninstall       Remove pre-commit hook
  --update          Update existing hook
  --status          Check hook installation status
  -h, --help        Show this help message

Examples:
  # Install hook
  bash tools/install-hooks.sh

  # Uninstall hook
  bash tools/install-hooks.sh --uninstall

  # Check status
  bash tools/install-hooks.sh --status

The pre-commit hook validates:
  - Manifest schema compliance
  - Policy schema compliance
  - Profile schema compliance (if present)
  - VaultID and GlyphSig format
  - Checksum correctness (if present)

Configuration:
  Create .mirrordna-hooks.conf in repo root to customize validation.
EOF
}

check_git_repo() {
    if [ ! -d "$REPO_ROOT/.git" ]; then
        echo -e "${RED}Error: Not a git repository${NC}"
        exit 1
    fi
}

create_hook() {
    cat > "$HOOK_FILE" <<'HOOK_SCRIPT'
#!/usr/bin/env bash
# MirrorDNA Pre-commit Hook
# Auto-generated by tools/install-hooks.sh
set -eo pipefail

# Configuration
REPO_ROOT="$(git rev-parse --show-toplevel)"
VALIDATORS_DIR="$REPO_ROOT/validators"
MANIFEST_FILE="$REPO_ROOT/mirrorDNA_manifest.yaml"
POLICY_FILE="$REPO_ROOT/reflection_policy.yaml"
PROFILE_FILE="$REPO_ROOT/continuity_profile.yaml"
CONFIG_FILE="$REPO_ROOT/.mirrordna-hooks.conf"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Load custom config if exists
if [ -f "$CONFIG_FILE" ]; then
    source "$CONFIG_FILE"
fi

# Check if validators are available
if [ ! -d "$VALIDATORS_DIR" ]; then
    echo -e "${YELLOW}⚠ MirrorDNA validators not found, skipping validation${NC}"
    exit 0
fi

# Check if Python is available
if ! command -v python3 &> /dev/null; then
    echo -e "${YELLOW}⚠ Python 3 not found, skipping validation${NC}"
    exit 0
fi

# Only validate if manifest exists
if [ ! -f "$MANIFEST_FILE" ]; then
    # Not a MirrorDNA project, skip validation
    exit 0
fi

echo "Running MirrorDNA compliance validation..."

# Build validation command
VALIDATE_CMD="python3 -m validators.cli --manifest $MANIFEST_FILE"

# Add policy if exists
if [ -f "$POLICY_FILE" ]; then
    VALIDATE_CMD="$VALIDATE_CMD --policy $POLICY_FILE"
fi

# Add profile if exists
if [ -f "$PROFILE_FILE" ]; then
    VALIDATE_CMD="$VALIDATE_CMD --profile $PROFILE_FILE"
fi

# Add no-color for cleaner output
VALIDATE_CMD="$VALIDATE_CMD --no-color"

# Run validation
if $VALIDATE_CMD; then
    echo -e "${GREEN}✓ MirrorDNA compliance validation passed${NC}"
    exit 0
else
    echo -e "${RED}✗ MirrorDNA compliance validation failed${NC}"
    echo ""
    echo "To fix issues:"
    echo "  1. Review errors above"
    echo "  2. Fix compliance issues"
    echo "  3. Try commit again"
    echo ""
    echo "To bypass (NOT recommended):"
    echo "  git commit --no-verify"
    echo ""
    exit 1
fi
HOOK_SCRIPT

    chmod +x "$HOOK_FILE"
}

install_hook() {
    check_git_repo

    if [ -f "$HOOK_FILE" ]; then
        echo -e "${YELLOW}Pre-commit hook already exists${NC}"
        echo "Use --update to replace it"
        exit 1
    fi

    echo "Installing MirrorDNA pre-commit hook..."

    # Ensure hooks directory exists
    mkdir -p "$HOOKS_DIR"

    # Create hook
    create_hook

    echo -e "${GREEN}✓ Pre-commit hook installed successfully${NC}"
    echo ""
    echo "The hook will:"
    echo "  - Validate manifest, policy, and profile before each commit"
    echo "  - Prevent commits if validation fails"
    echo "  - Can be bypassed with: git commit --no-verify"
    echo ""
    echo "To customize validation, create .mirrordna-hooks.conf"
}

uninstall_hook() {
    check_git_repo

    if [ ! -f "$HOOK_FILE" ]; then
        echo -e "${YELLOW}Pre-commit hook not installed${NC}"
        exit 0
    fi

    # Check if it's our hook
    if grep -q "MirrorDNA Pre-commit Hook" "$HOOK_FILE"; then
        rm "$HOOK_FILE"
        echo -e "${GREEN}✓ Pre-commit hook uninstalled successfully${NC}"
    else
        echo -e "${RED}Error: Existing pre-commit hook was not created by this tool${NC}"
        echo "Please remove manually if needed: $HOOK_FILE"
        exit 1
    fi
}

update_hook() {
    check_git_repo

    if [ ! -f "$HOOK_FILE" ]; then
        echo -e "${YELLOW}Pre-commit hook not installed, installing...${NC}"
        install_hook
        return
    fi

    # Check if it's our hook
    if ! grep -q "MirrorDNA Pre-commit Hook" "$HOOK_FILE"; then
        echo -e "${RED}Error: Existing pre-commit hook was not created by this tool${NC}"
        echo "Please remove manually before updating"
        exit 1
    fi

    echo "Updating MirrorDNA pre-commit hook..."
    create_hook
    echo -e "${GREEN}✓ Pre-commit hook updated successfully${NC}"
}

check_status() {
    check_git_repo

    echo "MirrorDNA Pre-commit Hook Status"
    echo "================================="

    if [ -f "$HOOK_FILE" ]; then
        if grep -q "MirrorDNA Pre-commit Hook" "$HOOK_FILE"; then
            echo -e "Status: ${GREEN}Installed ✓${NC}"
            echo "Location: $HOOK_FILE"
            if [ -x "$HOOK_FILE" ]; then
                echo -e "Executable: ${GREEN}Yes ✓${NC}"
            else
                echo -e "Executable: ${RED}No ✗${NC}"
            fi
        else
            echo -e "Status: ${YELLOW}Different hook installed${NC}"
            echo "Location: $HOOK_FILE"
            echo "Note: Hook was not created by this tool"
        fi
    else
        echo -e "Status: ${RED}Not installed ✗${NC}"
        echo "Run: bash tools/install-hooks.sh --install"
    fi
}

# Parse arguments
ACTION="install"

while [[ $# -gt 0 ]]; do
    case $1 in
        --install)
            ACTION="install"
            shift
            ;;
        --uninstall)
            ACTION="uninstall"
            shift
            ;;
        --update)
            ACTION="update"
            shift
            ;;
        --status)
            ACTION="status"
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
done

# Execute action
case $ACTION in
    install)
        install_hook
        ;;
    uninstall)
        uninstall_hook
        ;;
    update)
        update_hook
        ;;
    status)
        check_status
        ;;
esac
